spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 3

  jpa:
    show-sql: false

aura:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:5173,http://localhost:5174,https://aura-frontend-dun.vercel.app

app:
  base-url: https://aura-frontend-dun.vercel.app
  admin-key: ${ADMIN_KEY}