spring:
  application:
    name: aura-backend

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.time_zone: UTC
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: false
    clean-disabled: true
    locations: classpath:db/migration

gcp:
  project-id: project-5860f6a9-47e2-47ef-9e8
  bucket-name: aura-media-bucket-2026

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.openai.com/v1
  model: gpt-4o-mini
  connect-timeout-ms: 2000
  read-timeout-ms: 5000